### PR TITLE
Add GUI implementation

### PR DESCRIPTION
**Pull request by alexey-martynov**
Please find GUI dialogs for "Create Beam" and cut commands. The original implementation is very fragile and can be broken by selection of incorrect objects or incorrect clicks.

The new implementation relies on Select API and observer which allows usage of check boxes in model tree along with mouse clicks. The selected objects are subject of simple validation to avoid creation of faulty objects.

The following changes also included:
* Fixed icon for beams after cutting.
* Fixed icon for "Reload" command.
* Fixed reloading to avoid exception due to changing collection during iteration.
* README.md updated to describe GUI behaviour.

### CODE REVIEW

**Comment by looooo** [comment]
@alexey-martynov thanks for your work. I just merged another PR and now this PR has some conflicts. Can you resolve these conflicts? I see the conflicts are only in the readmee.md.

**Comment by alexey-martynov** [comment]
Thanks, I'll do this today or tomorrow

**Comment by alexey-martynov** [comment]
@looooo The conflicts are fixed.

**Comment by alexey-martynov** [comment]
@looooo 
I've added a sample with TechDraw usage and screenshots.

**Comment by looooo** [comment]
@alexey-martynov thanks, I just tried your branch and this looks much more user-friendly compared to the way I did the interface. Thanks a lot for this contribution.

**Comment by alexey-martynov** [comment]
@looooo You're welcome. I do many things from metal and wood in my country house and this workbench dramatically simplifies design from profiles like rectangle hollow pipe as shown in sample. So as software engineer I was unable to avoid improvement of UI here. Many thanks for implementation of cuts I'm not so good in such kind of math.

**Pull request merged**
