### PR TITLE
README.md reformatted and added content

### PR DESCRIPTION
**Pull request by luzpaz**
- tweaked markdown
- added sections
- fixed typos

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/freecad.frametools/blob/README/README.md

**Comment by luzpaz** [comment]
@looooo 

* what is the minimum version of scipy needed for this workbench?  
* Is there a forum thread that users can post to dedicated to this workbench that you prefer for them to use?  
* What are the Known Limitations of this workbench?

**Comment by luzpaz** [comment]
bump

**Comment by looooo** [comment]
sorry @luzpaz for ignoring this issue. I would like to have your motivation. ..

scipy is only needed for one function and some fem stuff. No idea about minimum version. Never had any problems. Some sparse functionality and a least-square solver are used

forum-thread and links:
heat 2d:
https://forum.freecadweb.org/viewtopic.php?f=18&t=32120
frame-tools:
https://forum.freecadweb.org/viewtopic.php?f=22&t=10892&hilit=pie+menu
https://vimeo.com/127369120
connection-tool:
https://forum.freecadweb.org/viewtopic.php?f=13&t=25512

known limitation:
It's more or less a set of tools to demonstrate work-flows and try different things. So it's not only about frames and beams...

**Pull request merged**
